/**
 * Tests for core models.
 */

import { describe, test, expect } from "bun:test";
import {
  MemoryType,
  RelationshipType,
  isMemoryType,
  isRelationshipType,
  createMemory,
  createRelationshipProperties,
  memoryToNodeProperties,
  ALL_MEMORY_TYPES,
  ALL_RELATIONSHIP_TYPES,
} from "../src/models.js";

describe("MemoryType", () => {
  test("has all expected types", () => {
    expect(MemoryType.TASK).toBe("task");
    expect(MemoryType.SOLUTION).toBe("solution");
    expect(MemoryType.PROBLEM).toBe("problem");
    expect(MemoryType.CODE_PATTERN).toBe("code_pattern");
  });

  test("isMemoryType validates correctly", () => {
    expect(isMemoryType("solution")).toBe(true);
    expect(isMemoryType("problem")).toBe(true);
    expect(isMemoryType("invalid")).toBe(false);
  });

  test("ALL_MEMORY_TYPES contains all types", () => {
    expect(ALL_MEMORY_TYPES.length).toBe(13);
    expect(ALL_MEMORY_TYPES).toContain("task");
    expect(ALL_MEMORY_TYPES).toContain("conversation");
  });
});

describe("RelationshipType", () => {
  test("has all expected types", () => {
    expect(RelationshipType.SOLVES).toBe("SOLVES");
    expect(RelationshipType.CAUSES).toBe("CAUSES");
    expect(RelationshipType.RELATED_TO).toBe("RELATED_TO");
  });

  test("isRelationshipType validates correctly", () => {
    expect(isRelationshipType("SOLVES")).toBe(true);
    expect(isRelationshipType("CAUSES")).toBe(true);
    expect(isRelationshipType("invalid")).toBe(false);
  });

  test("ALL_RELATIONSHIP_TYPES contains all types", () => {
    expect(ALL_RELATIONSHIP_TYPES.length).toBe(35);
  });
});

describe("createMemory", () => {
  test("creates memory with defaults", () => {
    const mem = createMemory({
      type: "solution",
      title: "Test Solution",
      content: "This is a test solution",
    });

    // ID is null until stored (generated by database layer)
    expect(mem.id).toBeNull();
    expect(mem.type).toBe("solution");
    expect(mem.title).toBe("Test Solution");
    expect(mem.content).toBe("This is a test solution");
    expect(mem.importance).toBe(0.5);
    expect(mem.confidence).toBe(0.8);
    expect(mem.usage_count).toBe(0);
    expect(mem.version).toBe(1);
    expect(mem.tags).toEqual([]);
  });

  test("creates memory with custom values", () => {
    const mem = createMemory({
      type: "problem",
      title: "Custom Problem",
      content: "A custom problem",
      tags: ["BUG", "Auth  "],
      importance: 0.9,
      confidence: 0.95,
    });

    expect(mem.type).toBe("problem");
    expect(mem.importance).toBe(0.9);
    expect(mem.confidence).toBe(0.95);
    // Tags should be lowercased and trimmed
    expect(mem.tags).toEqual(["bug", "auth"]);
  });

  test("creates memory with partial context", () => {
    const mem = createMemory({
      type: "solution",
      title: "With Context",
      content: "Has context",
      context: {
        project_path: "/my/project",
        languages: ["typescript"],
      },
    });

    expect(mem.context).toBeDefined();
    expect(mem.context!.project_path).toBe("/my/project");
    expect(mem.context!.languages).toEqual(["typescript"]);
    // Defaults should be applied
    expect(mem.context!.visibility).toBe("project");
  });
});

describe("createRelationshipProperties", () => {
  test("creates with defaults", () => {
    const props = createRelationshipProperties();
    expect(props.strength).toBe(0.5);
    expect(props.confidence).toBe(0.8);
    expect(props.evidence_count).toBe(1);
    expect(props.valid_until).toBeNull();
  });

  test("creates with overrides", () => {
    const props = createRelationshipProperties({
      strength: 0.9,
      confidence: 0.95,
      context: "test context",
    });
    expect(props.strength).toBe(0.9);
    expect(props.confidence).toBe(0.95);
    expect(props.context).toBe("test context");
  });
});

describe("memoryToNodeProperties", () => {
  test("converts memory to flat properties", () => {
    const mem = createMemory({
      id: "test-id",
      type: "solution",
      title: "Test",
      content: "Content",
      tags: ["tag1", "tag2"],
    });

    const props = memoryToNodeProperties(mem);
    expect(props["id"]).toBe("test-id");
    expect(props["type"]).toBe("solution");
    expect(props["title"]).toBe("Test");
    expect(props["content"]).toBe("Content");
    expect(props["tags"]).toEqual(["tag1", "tag2"]);
  });

  test("includes context properties with prefix", () => {
    const mem = createMemory({
      type: "solution",
      title: "Test",
      content: "Content",
      context: {
        project_path: "/my/project",
        languages: ["typescript"],
      },
    });

    const props = memoryToNodeProperties(mem);
    expect(props["context_project_path"]).toBe("/my/project");
    expect(props["context_languages"]).toEqual(["typescript"]);
  });
});
